# Welcome to Jekyll!

# Standard settings

# Site settings
title: Code with Us
email: julian@codewithus.tube
description: >- # this means to ignore newlines until "baseurl:"
  Code with Us helps newcomers to web development learn the basics by participating in and watching webinars and coding sessions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codewithustube
github_username:  codewithus

# Build settings
liquid:
  error_mode: strict
  # this makes checking for variable existence difficult
  # https://github.com/Shopify/liquid/issues/1034
  strict_variables: true
  strict_filters: true
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include:
  - _pages

header_pages:
  - _pages/about.md
  - _pages/blog.md
  - _pages/resources.md
  - _pages/forum.md

# To see a full list of default configuration settings: 
# https://jekyllrb.com/docs/configuration/default/
# To see an explanation of config options
# https://jekyllrb.com/docs/configuration/options/
